import { HydrationBoundary, dehydrate } from '@tanstack/react-query';
import './global.css';
import 'react-toastify/dist/ReactToastify.css';
import { Providers } from './Providers';
import { queryCurrentUser } from './queries/currentUser';
import { getQueryClient } from './queries/queryClient';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const queryClient = getQueryClient();
  await queryClient.prefetchQuery(queryCurrentUser());

  return (
    <html lang="en">
      <body>
        <Providers>
          <HydrationBoundary state={dehydrate(queryClient)}>
            {children}
          </HydrationBoundary>
        </Providers>
      </body>
    </html>
  );
}
